java_test(
    name = "options_test",
    srcs = glob(["*.java"]),
    test_class = "com.google.devtools.common.options.AllTests",
    size = "small",
    deps = [
        "//src/main/java/com/google/devtools/common/options",
        "//src/test/java/com/google/devtools/build/lib/testutil",
        "@com_google_guava_guava//jar",
        "@com_google_guava_guava_testlib//jar",
        "@com_google_truth_truth//jar",
        "@junit_junit4//jar",
        "@org_hamcrest_hamcrest_core//jar",
    ],
)
